export const GET_CHARACTER = "GET_CHARACTER";
export const CHARACTER_INFO = "CHARACTER_INFO";
export const CREATE_CHARACTER = "CREATE_CHARACTER";
export const SET_LOADING = "SET_LOADING";
export const GET_VOTES = "GET_VOTES";
